language: node_js
node_js:
- '0.10'
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: IbmLzkOA2L6+qubaayghZL8XalcMpWhSY0fYxGyAKPg6+nbYI530g98SMXTo6GvxX0UQXKl9cTWgUdYqv4BK21XWU7Xeleui8pO+PE5gIEgxtFf6LMeJQZoVMjqeBkzbBhOFBNCQKOjMZ5WAdu+hmFfsZIMWH9GeJq5I7D9XktU=
  app: openroads-api
  on:
    repo: opengovt/openroads-api
    branch: master
