postgres:
  image: openroads-db:test
  ports:
    - "5433:5432"
api:
  build: .
  environment:
    - DATABASE_URL=postgres://postgres@postgres:5432/postgres
    - WAIT_COMMAND= [ $$(psql postgres://postgres@postgres:5432/postgres -c "select count(*) from admin_boundaries" | head -n 3 | tail -n 1) -gt 0 ]
    - WAIT_SLEEP=2
    - WAIT_START_CMD=npm test
  links:
    - postgres:postgres
  ports:
    - "4000:4000"
