db:
  image: openroads-db:test
  ports:
    - "5433:5432"
api:
  build: .
  command: dockerize -wait tcp://db:5432 -timeout 20s npm start
  environment:
    - DATABASE_URL=postgres://postgres@db:5432/postgres
  links:
    - db
  ports:
    - "4000:4000"
